export enum IconEnum {
    'AddProductIcon' = 'assets/icons/add-product-icon.svg',
    'AddToCartIcon' = 'assets/icons/add-to-cart-icon.svg',
    'BackIcon' = 'assets/icons/back-icon.svg',
    'CheckOffIcon' = 'assets/icons/check-off-icon.svg',
    'CheckOnIcon' = 'assets/icons/check-on-icon.svg',
    'ChecksIcon' = 'assets/icons/checks-icon.svg',
    'CloseIcon' = 'assets/icons/close-icon.svg',
    'EditIcon' = 'assets/icons/edit-icon.svg',
    'EmailIcon' = 'assets/icons/email-icon.svg',
    'EyeIcon' = 'assets/icons/eye-icon.svg',
    'EyeSlashIcon' = 'assets/icons/eye-off-icon.svg',
    'ForgotpasswordIcon' = 'assets/icons/forgotpassword-icon.svg',
    'HomeIcon' = 'assets/icons/home-icon.svg',
    'LocationCheckIcon' = 'assets/icons/location-check-icon.svg',
    'LocationXmarkIcon' = 'assets/icons/location-xmark-icon.svg',
    'LockInputIcon' = 'assets/icons/lock-input-icon.svg',
    'MoveToTheNextIcon' = 'assets/icons/move-to-the-next-icon.svg',
    'ProfileIcon' = 'assets/icons/profile-icon.svg',
    'ResetPasswordIcon' = 'assets/icons/reset-password-icon.svg',
    'ShopIcon' = 'assets/icons/shop-icon.svg',
    'ShoppingCartIcon' = 'assets/icons/shopping-cart-icon.svg',
    'WarningCircleIcon' = 'assets/icons/warning-circle-icon.svg',
}
